# golangci-lint configuration file
version: "2"

linters:
  enable:
    - asasalint
    - asciicheck
    - bidichk
    - containedctx
    - contextcheck
    - copyloopvar
    - cyclop
    - decorder
    - dupword
    - errchkjson
    - errname
    - errorlint
    - exhaustive
    - funlen
    - gocognit
    - goconst
    - gocritic
    - gocyclo
    - godot
    - goprintffuncname
    - gosmopolitan
    - importas
    # - ireturn # Disabled because no problem with returning interfaces
    - lll
    - maintidx
    - makezero
    - mirror
    - misspell
    - nakedret
    - nestif
    - nilerr
    - nolintlint
    - reassign
    - revive
    - thelper
    - unconvert
    - unparam
    - usestdlibvars
    - wastedassign
    - whitespace

linters-settings:
  revive:
    rules:
      - name: var-naming
        disabled: true
