// Code generated by MockGen. DO NOT EDIT.
// Source: prompt.go
//
// Generated by this command:
//
//	mockgen -source=prompt.go -destination=mockprompt.gen.go -package=prompt
//

// Package prompt is a generated GoMock package.
package prompt

import (
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockPrompt is a mock of Prompt interface.
type MockPrompt struct {
	ctrl     *gomock.Controller
	recorder *MockPromptMockRecorder
	isgomock struct{}
}

// MockPromptMockRecorder is the mock recorder for MockPrompt.
type MockPromptMockRecorder struct {
	mock *MockPrompt
}

// NewMockPrompt creates a new mock instance.
func NewMockPrompt(ctrl *gomock.Controller) *MockPrompt {
	mock := &MockPrompt{ctrl: ctrl}
	mock.recorder = &MockPromptMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockPrompt) EXPECT() *MockPromptMockRecorder {
	return m.recorder
}

// PromptForBasePath mocks base method.
func (m *MockPrompt) PromptForBasePath() (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "PromptForBasePath")
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// PromptForBasePath indicates an expected call of PromptForBasePath.
func (mr *MockPromptMockRecorder) PromptForBasePath() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "PromptForBasePath", reflect.TypeOf((*MockPrompt)(nil).PromptForBasePath))
}

// PromptForConfirmation mocks base method.
func (m *MockPrompt) PromptForConfirmation(message string, defaultYes bool) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "PromptForConfirmation", message, defaultYes)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// PromptForConfirmation indicates an expected call of PromptForConfirmation.
func (mr *MockPromptMockRecorder) PromptForConfirmation(message, defaultYes any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "PromptForConfirmation", reflect.TypeOf((*MockPrompt)(nil).PromptForConfirmation), message, defaultYes)
}
