// Code generated by MockGen. DO NOT EDIT.
// Source: ide.go
//
// Generated by this command:
//
//	mockgen -source=ide.go -destination=mocks/ide.gen.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockIDE is a mock of IDE interface.
type MockIDE struct {
	ctrl     *gomock.Controller
	recorder *MockIDEMockRecorder
	isgomock struct{}
}

// MockIDEMockRecorder is the mock recorder for MockIDE.
type MockIDEMockRecorder struct {
	mock *MockIDE
}

// NewMockIDE creates a new mock instance.
func NewMockIDE(ctrl *gomock.Controller) *MockIDE {
	mock := &MockIDE{ctrl: ctrl}
	mock.recorder = &MockIDEMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockIDE) EXPECT() *MockIDEMockRecorder {
	return m.recorder
}

// IsInstalled mocks base method.
func (m *MockIDE) IsInstalled() bool {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "IsInstalled")
	ret0, _ := ret[0].(bool)
	return ret0
}

// IsInstalled indicates an expected call of IsInstalled.
func (mr *MockIDEMockRecorder) IsInstalled() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "IsInstalled", reflect.TypeOf((*MockIDE)(nil).IsInstalled))
}

// Name mocks base method.
func (m *MockIDE) Name() string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Name")
	ret0, _ := ret[0].(string)
	return ret0
}

// Name indicates an expected call of Name.
func (mr *MockIDEMockRecorder) Name() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Name", reflect.TypeOf((*MockIDE)(nil).Name))
}

// OpenRepository mocks base method.
func (m *MockIDE) OpenRepository(path string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "OpenRepository", path)
	ret0, _ := ret[0].(error)
	return ret0
}

// OpenRepository indicates an expected call of OpenRepository.
func (mr *MockIDEMockRecorder) OpenRepository(path any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "OpenRepository", reflect.TypeOf((*MockIDE)(nil).OpenRepository), path)
}
