// Code generated by MockGen. DO NOT EDIT.
// Source: manager.go
//
// Generated by this command:
//
//	mockgen -source=manager.go -destination=mocks/manager.gen.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	reflect "reflect"

	ide "github.com/lerenn/code-manager/pkg/hooks/ide"
	gomock "go.uber.org/mock/gomock"
)

// MockManagerInterface is a mock of ManagerInterface interface.
type MockManagerInterface struct {
	ctrl     *gomock.Controller
	recorder *MockManagerInterfaceMockRecorder
	isgomock struct{}
}

// MockManagerInterfaceMockRecorder is the mock recorder for MockManagerInterface.
type MockManagerInterfaceMockRecorder struct {
	mock *MockManagerInterface
}

// NewMockManagerInterface creates a new mock instance.
func NewMockManagerInterface(ctrl *gomock.Controller) *MockManagerInterface {
	mock := &MockManagerInterface{ctrl: ctrl}
	mock.recorder = &MockManagerInterfaceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockManagerInterface) EXPECT() *MockManagerInterfaceMockRecorder {
	return m.recorder
}

// GetIDE mocks base method.
func (m *MockManagerInterface) GetIDE(name string) (ide.IDE, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetIDE", name)
	ret0, _ := ret[0].(ide.IDE)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetIDE indicates an expected call of GetIDE.
func (mr *MockManagerInterfaceMockRecorder) GetIDE(name any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetIDE", reflect.TypeOf((*MockManagerInterface)(nil).GetIDE), name)
}

// OpenIDE mocks base method.
func (m *MockManagerInterface) OpenIDE(name, path string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "OpenIDE", name, path)
	ret0, _ := ret[0].(error)
	return ret0
}

// OpenIDE indicates an expected call of OpenIDE.
func (mr *MockManagerInterfaceMockRecorder) OpenIDE(name, path any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "OpenIDE", reflect.TypeOf((*MockManagerInterface)(nil).OpenIDE), name, path)
}
