// Code generated by MockGen. DO NOT EDIT.
// Source: manager.go
//
// Generated by this command:
//
//	mockgen -source=manager.go -destination=mocks/manager.gen.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	reflect "reflect"

	hooks "github.com/lerenn/code-manager/pkg/hooks"
	gomock "go.uber.org/mock/gomock"
)

// MockHookManagerInterface is a mock of HookManagerInterface interface.
type MockHookManagerInterface struct {
	ctrl     *gomock.Controller
	recorder *MockHookManagerInterfaceMockRecorder
	isgomock struct{}
}

// MockHookManagerInterfaceMockRecorder is the mock recorder for MockHookManagerInterface.
type MockHookManagerInterfaceMockRecorder struct {
	mock *MockHookManagerInterface
}

// NewMockHookManagerInterface creates a new mock instance.
func NewMockHookManagerInterface(ctrl *gomock.Controller) *MockHookManagerInterface {
	mock := &MockHookManagerInterface{ctrl: ctrl}
	mock.recorder = &MockHookManagerInterfaceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockHookManagerInterface) EXPECT() *MockHookManagerInterfaceMockRecorder {
	return m.recorder
}

// ExecuteErrorHooks mocks base method.
func (m *MockHookManagerInterface) ExecuteErrorHooks(operation string, ctx *hooks.HookContext) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ExecuteErrorHooks", operation, ctx)
	ret0, _ := ret[0].(error)
	return ret0
}

// ExecuteErrorHooks indicates an expected call of ExecuteErrorHooks.
func (mr *MockHookManagerInterfaceMockRecorder) ExecuteErrorHooks(operation, ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ExecuteErrorHooks", reflect.TypeOf((*MockHookManagerInterface)(nil).ExecuteErrorHooks), operation, ctx)
}

// ExecutePostHooks mocks base method.
func (m *MockHookManagerInterface) ExecutePostHooks(operation string, ctx *hooks.HookContext) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ExecutePostHooks", operation, ctx)
	ret0, _ := ret[0].(error)
	return ret0
}

// ExecutePostHooks indicates an expected call of ExecutePostHooks.
func (mr *MockHookManagerInterfaceMockRecorder) ExecutePostHooks(operation, ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ExecutePostHooks", reflect.TypeOf((*MockHookManagerInterface)(nil).ExecutePostHooks), operation, ctx)
}

// ExecutePostWorktreeCheckoutHooks mocks base method.
func (m *MockHookManagerInterface) ExecutePostWorktreeCheckoutHooks(operation string, ctx *hooks.HookContext) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ExecutePostWorktreeCheckoutHooks", operation, ctx)
	ret0, _ := ret[0].(error)
	return ret0
}

// ExecutePostWorktreeCheckoutHooks indicates an expected call of ExecutePostWorktreeCheckoutHooks.
func (mr *MockHookManagerInterfaceMockRecorder) ExecutePostWorktreeCheckoutHooks(operation, ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ExecutePostWorktreeCheckoutHooks", reflect.TypeOf((*MockHookManagerInterface)(nil).ExecutePostWorktreeCheckoutHooks), operation, ctx)
}

// ExecutePreHooks mocks base method.
func (m *MockHookManagerInterface) ExecutePreHooks(operation string, ctx *hooks.HookContext) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ExecutePreHooks", operation, ctx)
	ret0, _ := ret[0].(error)
	return ret0
}

// ExecutePreHooks indicates an expected call of ExecutePreHooks.
func (mr *MockHookManagerInterfaceMockRecorder) ExecutePreHooks(operation, ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ExecutePreHooks", reflect.TypeOf((*MockHookManagerInterface)(nil).ExecutePreHooks), operation, ctx)
}

// ExecutePreWorktreeCreationHooks mocks base method.
func (m *MockHookManagerInterface) ExecutePreWorktreeCreationHooks(operation string, ctx *hooks.HookContext) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ExecutePreWorktreeCreationHooks", operation, ctx)
	ret0, _ := ret[0].(error)
	return ret0
}

// ExecutePreWorktreeCreationHooks indicates an expected call of ExecutePreWorktreeCreationHooks.
func (mr *MockHookManagerInterfaceMockRecorder) ExecutePreWorktreeCreationHooks(operation, ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ExecutePreWorktreeCreationHooks", reflect.TypeOf((*MockHookManagerInterface)(nil).ExecutePreWorktreeCreationHooks), operation, ctx)
}

// RegisterPostHook mocks base method.
func (m *MockHookManagerInterface) RegisterPostHook(operation string, hook hooks.PostHook) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RegisterPostHook", operation, hook)
	ret0, _ := ret[0].(error)
	return ret0
}

// RegisterPostHook indicates an expected call of RegisterPostHook.
func (mr *MockHookManagerInterfaceMockRecorder) RegisterPostHook(operation, hook any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RegisterPostHook", reflect.TypeOf((*MockHookManagerInterface)(nil).RegisterPostHook), operation, hook)
}

// RegisterPostWorktreeCheckoutHook mocks base method.
func (m *MockHookManagerInterface) RegisterPostWorktreeCheckoutHook(operation string, hook hooks.PostWorktreeCheckoutHook) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RegisterPostWorktreeCheckoutHook", operation, hook)
	ret0, _ := ret[0].(error)
	return ret0
}

// RegisterPostWorktreeCheckoutHook indicates an expected call of RegisterPostWorktreeCheckoutHook.
func (mr *MockHookManagerInterfaceMockRecorder) RegisterPostWorktreeCheckoutHook(operation, hook any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RegisterPostWorktreeCheckoutHook", reflect.TypeOf((*MockHookManagerInterface)(nil).RegisterPostWorktreeCheckoutHook), operation, hook)
}

// RegisterPreWorktreeCreationHook mocks base method.
func (m *MockHookManagerInterface) RegisterPreWorktreeCreationHook(operation string, hook hooks.PreWorktreeCreationHook) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RegisterPreWorktreeCreationHook", operation, hook)
	ret0, _ := ret[0].(error)
	return ret0
}

// RegisterPreWorktreeCreationHook indicates an expected call of RegisterPreWorktreeCreationHook.
func (mr *MockHookManagerInterfaceMockRecorder) RegisterPreWorktreeCreationHook(operation, hook any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RegisterPreWorktreeCreationHook", reflect.TypeOf((*MockHookManagerInterface)(nil).RegisterPreWorktreeCreationHook), operation, hook)
}
