// Code generated by MockGen. DO NOT EDIT.
// Source: manager.go
//
// Generated by this command:
//
//	mockgen -source=manager.go -destination=mocks/manager.gen.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	reflect "reflect"

	hooks "github.com/lerenn/code-manager/pkg/hooks"
	gomock "go.uber.org/mock/gomock"
)

// MockHookManagerInterface is a mock of HookManagerInterface interface.
type MockHookManagerInterface struct {
	ctrl     *gomock.Controller
	recorder *MockHookManagerInterfaceMockRecorder
	isgomock struct{}
}

// MockHookManagerInterfaceMockRecorder is the mock recorder for MockHookManagerInterface.
type MockHookManagerInterfaceMockRecorder struct {
	mock *MockHookManagerInterface
}

// NewMockHookManagerInterface creates a new mock instance.
func NewMockHookManagerInterface(ctrl *gomock.Controller) *MockHookManagerInterface {
	mock := &MockHookManagerInterface{ctrl: ctrl}
	mock.recorder = &MockHookManagerInterfaceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockHookManagerInterface) EXPECT() *MockHookManagerInterfaceMockRecorder {
	return m.recorder
}

// ExecuteErrorHooks mocks base method.
func (m *MockHookManagerInterface) ExecuteErrorHooks(operation string, ctx *hooks.HookContext) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ExecuteErrorHooks", operation, ctx)
	ret0, _ := ret[0].(error)
	return ret0
}

// ExecuteErrorHooks indicates an expected call of ExecuteErrorHooks.
func (mr *MockHookManagerInterfaceMockRecorder) ExecuteErrorHooks(operation, ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ExecuteErrorHooks", reflect.TypeOf((*MockHookManagerInterface)(nil).ExecuteErrorHooks), operation, ctx)
}

// ExecutePostHooks mocks base method.
func (m *MockHookManagerInterface) ExecutePostHooks(operation string, ctx *hooks.HookContext) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ExecutePostHooks", operation, ctx)
	ret0, _ := ret[0].(error)
	return ret0
}

// ExecutePostHooks indicates an expected call of ExecutePostHooks.
func (mr *MockHookManagerInterfaceMockRecorder) ExecutePostHooks(operation, ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ExecutePostHooks", reflect.TypeOf((*MockHookManagerInterface)(nil).ExecutePostHooks), operation, ctx)
}

// ExecutePreHooks mocks base method.
func (m *MockHookManagerInterface) ExecutePreHooks(operation string, ctx *hooks.HookContext) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ExecutePreHooks", operation, ctx)
	ret0, _ := ret[0].(error)
	return ret0
}

// ExecutePreHooks indicates an expected call of ExecutePreHooks.
func (mr *MockHookManagerInterfaceMockRecorder) ExecutePreHooks(operation, ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ExecutePreHooks", reflect.TypeOf((*MockHookManagerInterface)(nil).ExecutePreHooks), operation, ctx)
}

// ExecuteWorktreeCheckoutHooks mocks base method.
func (m *MockHookManagerInterface) ExecuteWorktreeCheckoutHooks(operation string, ctx *hooks.HookContext) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ExecuteWorktreeCheckoutHooks", operation, ctx)
	ret0, _ := ret[0].(error)
	return ret0
}

// ExecuteWorktreeCheckoutHooks indicates an expected call of ExecuteWorktreeCheckoutHooks.
func (mr *MockHookManagerInterfaceMockRecorder) ExecuteWorktreeCheckoutHooks(operation, ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ExecuteWorktreeCheckoutHooks", reflect.TypeOf((*MockHookManagerInterface)(nil).ExecuteWorktreeCheckoutHooks), operation, ctx)
}

// RegisterPostHook mocks base method.
func (m *MockHookManagerInterface) RegisterPostHook(operation string, hook hooks.PostHook) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RegisterPostHook", operation, hook)
	ret0, _ := ret[0].(error)
	return ret0
}

// RegisterPostHook indicates an expected call of RegisterPostHook.
func (mr *MockHookManagerInterfaceMockRecorder) RegisterPostHook(operation, hook any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RegisterPostHook", reflect.TypeOf((*MockHookManagerInterface)(nil).RegisterPostHook), operation, hook)
}

// RegisterWorktreeCheckoutHook mocks base method.
func (m *MockHookManagerInterface) RegisterWorktreeCheckoutHook(operation string, hook hooks.WorktreeCheckoutHook) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RegisterWorktreeCheckoutHook", operation, hook)
	ret0, _ := ret[0].(error)
	return ret0
}

// RegisterWorktreeCheckoutHook indicates an expected call of RegisterWorktreeCheckoutHook.
func (mr *MockHookManagerInterfaceMockRecorder) RegisterWorktreeCheckoutHook(operation, hook any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RegisterWorktreeCheckoutHook", reflect.TypeOf((*MockHookManagerInterface)(nil).RegisterWorktreeCheckoutHook), operation, hook)
}
