// Code generated by MockGen. DO NOT EDIT.
// Source: prompt.go
//
// Generated by this command:
//
//	mockgen -source=prompt.go -destination=mocks/prompt.gen.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockPrompter is a mock of Prompter interface.
type MockPrompter struct {
	ctrl     *gomock.Controller
	recorder *MockPrompterMockRecorder
	isgomock struct{}
}

// MockPrompterMockRecorder is the mock recorder for MockPrompter.
type MockPrompterMockRecorder struct {
	mock *MockPrompter
}

// NewMockPrompter creates a new mock instance.
func NewMockPrompter(ctrl *gomock.Controller) *MockPrompter {
	mock := &MockPrompter{ctrl: ctrl}
	mock.recorder = &MockPrompterMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockPrompter) EXPECT() *MockPrompterMockRecorder {
	return m.recorder
}

// PromptForBasePath mocks base method.
func (m *MockPrompter) PromptForBasePath(defaultBasePath string) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "PromptForBasePath", defaultBasePath)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// PromptForBasePath indicates an expected call of PromptForBasePath.
func (mr *MockPrompterMockRecorder) PromptForBasePath(defaultBasePath any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "PromptForBasePath", reflect.TypeOf((*MockPrompter)(nil).PromptForBasePath), defaultBasePath)
}

// PromptForConfirmation mocks base method.
func (m *MockPrompter) PromptForConfirmation(message string, defaultYes bool) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "PromptForConfirmation", message, defaultYes)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// PromptForConfirmation indicates an expected call of PromptForConfirmation.
func (mr *MockPrompterMockRecorder) PromptForConfirmation(message, defaultYes any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "PromptForConfirmation", reflect.TypeOf((*MockPrompter)(nil).PromptForConfirmation), message, defaultYes)
}
