// Code generated by MockGen. DO NOT EDIT.
// Source: manager.go
//
// Generated by this command:
//
//	mockgen -source=manager.go -destination=mocks/manager.gen.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	reflect "reflect"

	config "github.com/lerenn/code-manager/pkg/config"
	gomock "go.uber.org/mock/gomock"
)

// MockManager is a mock of Manager interface.
type MockManager struct {
	ctrl     *gomock.Controller
	recorder *MockManagerMockRecorder
	isgomock struct{}
}

// MockManagerMockRecorder is the mock recorder for MockManager.
type MockManagerMockRecorder struct {
	mock *MockManager
}

// NewMockManager creates a new mock instance.
func NewMockManager(ctrl *gomock.Controller) *MockManager {
	mock := &MockManager{ctrl: ctrl}
	mock.recorder = &MockManagerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockManager) EXPECT() *MockManagerMockRecorder {
	return m.recorder
}

// CreateConfigDirectory mocks base method.
func (m *MockManager) CreateConfigDirectory() error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateConfigDirectory")
	ret0, _ := ret[0].(error)
	return ret0
}

// CreateConfigDirectory indicates an expected call of CreateConfigDirectory.
func (mr *MockManagerMockRecorder) CreateConfigDirectory() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateConfigDirectory", reflect.TypeOf((*MockManager)(nil).CreateConfigDirectory))
}

// DefaultConfig mocks base method.
func (m *MockManager) DefaultConfig() config.Config {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DefaultConfig")
	ret0, _ := ret[0].(config.Config)
	return ret0
}

// DefaultConfig indicates an expected call of DefaultConfig.
func (mr *MockManagerMockRecorder) DefaultConfig() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DefaultConfig", reflect.TypeOf((*MockManager)(nil).DefaultConfig))
}

// GetConfig mocks base method.
func (m *MockManager) GetConfig() (config.Config, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetConfig")
	ret0, _ := ret[0].(config.Config)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetConfig indicates an expected call of GetConfig.
func (mr *MockManagerMockRecorder) GetConfig() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetConfig", reflect.TypeOf((*MockManager)(nil).GetConfig))
}

// GetConfigPath mocks base method.
func (m *MockManager) GetConfigPath() string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetConfigPath")
	ret0, _ := ret[0].(string)
	return ret0
}

// GetConfigPath indicates an expected call of GetConfigPath.
func (mr *MockManagerMockRecorder) GetConfigPath() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetConfigPath", reflect.TypeOf((*MockManager)(nil).GetConfigPath))
}

// GetConfigStrict mocks base method.
func (m *MockManager) GetConfigStrict() (config.Config, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetConfigStrict")
	ret0, _ := ret[0].(config.Config)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetConfigStrict indicates an expected call of GetConfigStrict.
func (mr *MockManagerMockRecorder) GetConfigStrict() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetConfigStrict", reflect.TypeOf((*MockManager)(nil).GetConfigStrict))
}

// GetConfigWithFallback mocks base method.
func (m *MockManager) GetConfigWithFallback() (config.Config, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetConfigWithFallback")
	ret0, _ := ret[0].(config.Config)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetConfigWithFallback indicates an expected call of GetConfigWithFallback.
func (mr *MockManagerMockRecorder) GetConfigWithFallback() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetConfigWithFallback", reflect.TypeOf((*MockManager)(nil).GetConfigWithFallback))
}

// SaveConfig mocks base method.
func (m *MockManager) SaveConfig(arg0 config.Config) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SaveConfig", arg0)
	ret0, _ := ret[0].(error)
	return ret0
}

// SaveConfig indicates an expected call of SaveConfig.
func (mr *MockManagerMockRecorder) SaveConfig(arg0 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SaveConfig", reflect.TypeOf((*MockManager)(nil).SaveConfig), arg0)
}

// SetConfigPath mocks base method.
func (m *MockManager) SetConfigPath(configPath string) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "SetConfigPath", configPath)
}

// SetConfigPath indicates an expected call of SetConfigPath.
func (mr *MockManagerMockRecorder) SetConfigPath(configPath any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetConfigPath", reflect.TypeOf((*MockManager)(nil).SetConfigPath), configPath)
}

// ValidateRepositoriesDir mocks base method.
func (m *MockManager) ValidateRepositoriesDir(repositoriesDir string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ValidateRepositoriesDir", repositoriesDir)
	ret0, _ := ret[0].(error)
	return ret0
}

// ValidateRepositoriesDir indicates an expected call of ValidateRepositoriesDir.
func (mr *MockManagerMockRecorder) ValidateRepositoriesDir(repositoriesDir any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ValidateRepositoriesDir", reflect.TypeOf((*MockManager)(nil).ValidateRepositoriesDir), repositoriesDir)
}

// ValidateStatusFile mocks base method.
func (m *MockManager) ValidateStatusFile(statusFile string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ValidateStatusFile", statusFile)
	ret0, _ := ret[0].(error)
	return ret0
}

// ValidateStatusFile indicates an expected call of ValidateStatusFile.
func (mr *MockManagerMockRecorder) ValidateStatusFile(statusFile any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ValidateStatusFile", reflect.TypeOf((*MockManager)(nil).ValidateStatusFile), statusFile)
}

// ValidateWorkspacesDir mocks base method.
func (m *MockManager) ValidateWorkspacesDir(workspacesDir string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ValidateWorkspacesDir", workspacesDir)
	ret0, _ := ret[0].(error)
	return ret0
}

// ValidateWorkspacesDir indicates an expected call of ValidateWorkspacesDir.
func (mr *MockManagerMockRecorder) ValidateWorkspacesDir(workspacesDir any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ValidateWorkspacesDir", reflect.TypeOf((*MockManager)(nil).ValidateWorkspacesDir), workspacesDir)
}
